#cloud-config

write_files:
-   content: |
        # rons test file
    owner: ubuntu:ubuntu
    path: /home/ubuntu/test.file
    permissions: 0755
    
packages:
 - python-pip
 - git
 - python-django
 
runcmd:
 - [ echo, "what" ]